### ISSUE TITLE
Lazy load

### ISSUE THREAD

**Issue by MaikCape** [tieniber/DataGridColumnSearch#11]
When using the widget in grids on tabpages, all the data is loaded when opening this page, this will make it very slow. The standard functionality of mendix is to load the data of the tabpage when opening the tab. 

This 'Lazy loading' functionality would be a great adjustement to the widget.

**Comment by cdcharlebois** [comment]
Seems like the functionality in the widget to check to see if the widget has been loaded yet always returns true. [Line 48](https://github.com/tieniber/DataGridColumnSearch/blob/master/src/DataGridColumnSearch/widget/DataGridColumnSearch.js#L48). Furthermore, `postCreate` is called for widgets when the page loads even if the widget is contained in a tab that is not active. Further research into this is required to find a better way to do this

**Comment by MaikCape** [comment]
Can you give an update about this issue?

**Comment by tieniber** [comment]
Per Mendix R&D, the presence of a custom widget in a tab forces it to fully load. So, this unfortunately isn't possible today. I recommend a solution using multiple pages instead of tabs.
