### ISSUE TITLE
Could not create widget DataGridColumnSearch.widget.DataGridColumnSearch 

### ISSUE THREAD

**Issue by dhoogea** [tieniber/DataGridColumnSearch#16]
error:Could not create widget DataGridColumnSearch.widget.DataGridColumnSearch
GRID Entity: GWSAMPLE_BASIC.SalesOrder

where the grid is showing a list of  GWSAMPLE_BASIC. SalesOrder

**Comment by tieniber** [comment]
Usually happens because you need to drop the widget below/after the data
grid.

**Comment by tieniber** [comment]
Stale issue, closing. Please provide more information in order to reproduce this if this is still an open issue.
