### ISSUE TITLE
Could not create widget DataGridColumnSearch.widget.DataGridColumnSearch

### ISSUE THREAD

**Issue by rajnish87k** [tieniber/DataGridColumnSearch#17]
I am getting the same error: Could not create widget DataGridColumnSearch.widget.DataGridColumnSearc,
While using the date as a column in Datagrid for the 8.4.2 version

**Comment by mbusger** [comment]
I'm also having this issue in Mendix 8. Is there a timetable for getting the widget to work again in Mendix 8?

**Comment by tieniber** [comment]
Fixed in v2.0.0
