### ISSUE TITLE
Mx 7.5.x compatibility

### ISSUE THREAD

**Issue by mkumpf** [tieniber/DataGridColumnSearch#8]
Eric,
Will you be able to update this widget to work with the latest versions of Mendix?  I am getting ready to upgrade and app and figuring out if I will need to remove this widget.
Thanks,
Mike

**Comment by tieniber** [comment]
@mkumpf, we fixed this, correct?

**Comment by mkumpf** [comment]
Yup - I have it running successfully on 7.10 (will try 7.11 next week)
